// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUwXDQK_BwnRp87H01oMxG9FTKQl1d3lg',
    appId: '1:587678856071:web:9c12507568753f97c85922',
    messagingSenderId: '587678856071',
    projectId: 'baakhapaa-flutter',
    authDomain: 'baakhapaa-flutter.firebaseapp.com',
    storageBucket: 'baakhapaa-flutter.appspot.com',
    measurementId: 'G-G20LH9Y106',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXgrq-mVlBFhm88X9AcU4o_HECBBReYJ4',
    appId: '1:587678856071:android:878b62bca67648e3c85922',
    messagingSenderId: '587678856071',
    projectId: 'baakhapaa-flutter',
    storageBucket: 'baakhapaa-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4S-JK_gY73LL6r4elhrRT8oCsjy9VIus',
    appId: '1:587678856071:ios:04d953d00498095cc85922',
    messagingSenderId: '587678856071',
    projectId: 'baakhapaa-flutter',
    storageBucket: 'baakhapaa-flutter.appspot.com',
    androidClientId:
        '587678856071-mth3vepd88i97t7uek79dupgh1j2g8i7.apps.googleusercontent.com',
    iosClientId:
        '587678856071-8lortqjd8fcro7d6b92t3q1pn4e8k40a.apps.googleusercontent.com',
    iosBundleId: 'com.baakhapaa.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4S-JK_gY73LL6r4elhrRT8oCsjy9VIus',
    appId: '1:587678856071:ios:2b71313834447e67c85922',
    messagingSenderId: '587678856071',
    projectId: 'baakhapaa-flutter',
    storageBucket: 'baakhapaa-flutter.appspot.com',
    androidClientId:
        '587678856071-mth3vepd88i97t7uek79dupgh1j2g8i7.apps.googleusercontent.com',
    iosClientId:
        '587678856071-cd45gc2v591glv3hoctt9bu0etf2u2d6.apps.googleusercontent.com',
    iosBundleId: 'com.baakhapaa.com',
  );
}
